name: Checks

on:
  push:
  pull_request:
  schedule:
    - cron: '22 20 * * 6'

jobs:
  py-lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: dmamontov/hass-py-lint@master
        with:
          path: "tests"